# env params
env:
  id: "dm_control/cheetah-run-v0"
  variant: "mlp_sa_env"
  num_envs: 8

# replay buffer params
replay_buffer:
  mem_size: 500000
  mode: "torch"
  use_dict_wrapper: false
  store_on_device: true
  random_rollover: true

# algorithm params
algorithm:
  variant: "simba"
  actor:
    embed_dim: 64
    num_blocks: 1
  critic:
    embed_dim: 256
    num_blocks: 2
  qu_num_ensemble: 2
  batch_size: 2048
  grad_steps_per_update: 1000
  actor_learning_rate: 0.003
  critic_learning_rate: 0.003
  alpha_learning_rate: 0.01
  target_smoothing_coefficient: 0.005
  tune_entropy: true
  target_entropy_gain: 1.0
  learn_uncertainty: true
  discount_factor: 0.99
  actor_update_ratio: 1
  critic_update_ratio: 1

# training config
runner:
  variant: "sync"
  max_transitions: 1000000
  transitions_per_epoch: 8000
  transitions_num_exploration: 25000
  transitions_min_for_train: 50000
  eval_num_episodes: 16
  eval_transitions_frequency: 8000

# https://github.com/jjshoots/Wingman?tab=readme-ov-file#from-wingman-import-wingman
mode:
  debug: false
  train: false
  eval: false
  display: false
  render: false

model:
  save_directory: "weights"
  id: ""
  ckpt: 0
  increment_ckpt: false

logging:
  interval: 10
  max_skips: 5
  greater_than: 0.0
  filename: ""

wandb:
  enable: false
  save_code: false
  run:
    name: "half_cheetah"
    notes: ""
  project:
    name: "dogfighter"
    entity: "jjshoots"
