# env params
env_type: "vec_env"
num_envs: 8
env_name: "dm_control/hopper-hop-v0"

# learning params
env_transitions_per_epoch: 8000
model_updates_per_epoch: 1000
buffer_size: 1500000
batch_size: 2048
total_steps: 2500000
critic_update_multiplier: 1
actor_update_multiplier: 1
discount_factor: 0.98
learning_rate: 0.003
exploration_steps: 25000
min_transitions_before_training: 50000
random_rollover: true
replay_buffer_mode: "torch"
replay_buffer_store_on_device: true

# CCGE params
pretrained_oracle: false
update_oracle: true
confidence_lambda: 0.1

# Model params
qu_num_ensemble: 2
embed_dim: 256

# eval settings
eval_num_episodes: 10
eval_steps_ratio: 8000

# wingman required params
# https://github.com/jjshoots/Wingman?tab=readme-ov-file#from-wingman-import-wingman
mode:
  debug: false
  train: false
  eval: false
  display: false

model:
  save_directory: "weights"
  id: ""
  ckpt: 0
  increment_ckpt: false

logging:
  interval: 10
  max_skips: 5
  greater_than: 0.0
  filename: ""

wandb:
  enable: false
  save_code: false
  run:
    name: "dm_control/hopper-hop-v0"
    notes: ""
  project:
    name: "dogfighter"
    entity: "jjshoots"
